# Generated by Django 3.0.6 on 2020-05-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='note_id',
            new_name='note',
        ),
    ]
