# Generated by Django 3.0.6 on 2020-05-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_remove_note_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='mod_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
